name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Compressarr-$tag"

          # Build everything
          dotnet publish -c Release -o "$release_name"

          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          
          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Compressarr*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
